server:
  port: 8083
dubbo:
  application:
    name: item_web
  registry:
    address: zookeeper://39.108.188.42:2181
  consumer:
    check: false
    timeout: 10000

spring:
  rabbitmq:
    host: 39.108.188.42
    virtual-host: /
