server:
  port: 8083
dubbo:
  application:
    name: item_web
  registry:
    address: zookeeper://120.79.167.170:2181
  consumer:
    check: false
    timeout: 10000

spring:
  rabbitmq:
    host: 120.79.167.170
    virtual-host: /
