server:
  port: 8080
spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
dubbo:
  application:
    name: back_web
  registry:
    address: zookeeper://39.108.188.42:2181
  consumer:
    check: false
upload:
  path: D:/img/