server:
  port: 8080
spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
dubbo:
  application:
    name: back_web
  registry:
    address: zookeeper://120.79.167.170:2181
  consumer:
    check: false
upload:
  path: D:/img/

fdfs:
  so-timeout: 10000
  connect-timeout: 10000
  tracker-list:
    - 120.79.167.170:22122
  thumb-image:
    width: 100
    height: 100
  pool:
    jmx-enabled: false