server:
  port: 8082
spring:
  thymeleaf:
    cache: false
dubbo:
  application:
    name: search_web
  registry:
    address: zookeepper://120.79.167.170:2181
  consumer:
    check: false
    timeout: 10000
    retries: 3