spring:
  datasource:
    url: jdbc:mysql:///shop1903?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 39.108.188.42
    virtual-host: /
dubbo:
  application:
    name: goods_service
  registry:
    address: zookeeper://39.108.188.42:2181
  protocol:
    port: -1
    name: dubbo
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
