spring:
  datasource:
    url: jdbc:mysql:///shop1903?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 120.79.167.170
    virtual-host: /
dubbo:
  application:
    name: goods_service
  registry:
    address: zookeeper://120.79.167.170:2181
  protocol:
    port: -1
    name: dubbo
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
