dubbo:
  registry:
    address: zookeeper://120.79.167.170:2181
  protocol:
    name: dubbo
    port: -1
  application:
    name: searcher_service
spring:
  data:
    solr:
      host: http://120.79.167.170:8983/solr/mycollection
  rabbitmq:
    host: 120.79.167.170
    virtual-host: /