dubbo:
  registry:
    address: zookeeper://39.108.188.42:2181
  protocol:
    name: dubbo
    port: -1
  application:
    name: searcher_service
spring:
  data:
    solr:
      host: http://39.108.188.42:8983/solr/mycollection
  rabbitmq:
    host: 39.108.188.42
    virtual-host: /