server:
  port: 8084
spring:
  rabbitmq:
    host: 120.79.167.170
    virtual-host: /
  redis:
    host: 120.79.167.170
    password: root
dubbo:
  application:
    name: sso_web
  registry:
    address: zookeeper://120.79.167.170:2181
  consumer:
    check: false
    timeout: 10000